export interface Character {
  id: string;
  name: string;
  gender: string;
  age: number;
  mbti: string;
  personality: string;
  characteristics: string;
  affiliation: string;
  aura: string;
  combatPower: string;
  speechStyle: string;
  weapon: string;
  appearance: string;
  imageCode: string;
}

export const CHARACTERS: Character[] = [
  {
    id: 'c',
    name: '블리드',
    gender: '여',
    age: 33,
    mbti: 'ENTJ',
    personality: '오만함, 효율주의, 약육강식',
    characteristics: '적성회 간부, 카리스마, 뛰어난 전술, 전투에 능숙',
    affiliation: '적성회',
    aura: '혈액조작(최대 음속으로 혈액을 발사)',
    combatPower: 'S+',
    speechStyle: '나른하고 여유로운 반말',
    weapon: '없음',
    appearance: '창백한 피부, 적안, 은색 단발',
    imageCode: 'c',
  },
  {
    id: 'd',
    name: '데스롤',
    gender: '남',
    age: 26,
    mbti: 'ESTP',
    personality: '쾌락주의, 충동적인',
    characteristics: '적성회 간부, 가벼움 속의 잔혹함, 아드레날린 중독자, 파괴와 혼란을 즐김',
    affiliation: '적성회',
    aura: '폭발(원하는 대상에게 폭발을 일으킴)',
    combatPower: 'A+',
    speechStyle: '하이텐션의 가벼운 반말',
    weapon: '없음',
    appearance: '은발, 적안',
    imageCode: 'd',
  },
  {
    id: 'g',
    name: '레바인',
    gender: '여',
    age: 25,
    mbti: 'ISTJ',
    personality: '기계적인, 효율적, 무자비한',
    characteristics: 'A구 이사, \'A\'의 의지를 대리하는 집행관, 고도로 정제된 살의, \'A\'에게 절대 충성',
    affiliation: 'A구 관리국',
    aura: '혈참격(피를 머금은 검기로 모든 것을 절단)',
    combatPower: 'SSS-',
    speechStyle: '감정이 완벽히 배제된 극존칭',
    weapon: '카타나',
    appearance: '흑색 장발, 적안',
    imageCode: 'g',
  },
  {
    id: 'j',
    name: '프로스트',
    gender: '여',
    age: 27,
    mbti: 'INTJ',
    personality: '허무주의, 이성적',
    characteristics: '전 B구 이사, \'B\'의 허망한 죽음을 체념한 상태, 지저분한 전투를 혐오',
    affiliation: 'A구 관리국',
    aura: '냉기(대기 중의 수분이나 상대의 혈액 등을 순식간에 얼림)',
    combatPower: 'SS-',
    speechStyle: '온기가 없는 존댓말, 단호한 통보',
    weapon: '없음',
    appearance: '은색 장발, 청안',
    imageCode: 'j',
  },
  {
    id: 'h',
    name: '루미너스',
    gender: '여',
    age: 26,
    mbti: 'INTP',
    personality: '무감각한, 인간성 결여, 기계적',
    characteristics: 'F구 이사, 죄책감이 없음, 모든 걸 데이터로 인식',
    affiliation: 'F구 관리국',
    aura: '뇌전(푸른 벼락을 이용한 초정밀/광역 살상 능력)',
    combatPower: 'SS+',
    speechStyle: '무미건조한 반말, 시스템 용어를 차용한 통보',
    weapon: '없음',
    appearance: '흑발, 청안, 장발',
    imageCode: 'h',
  },
  {
    id: 'k',
    name: '제인',
    gender: '여',
    age: 31,
    mbti: 'ISTP',
    personality: '완벽주의, 합리적, 계산적',
    characteristics: 'D구 이사, 표적 사냥에 특화, 무뚝뚝함, 현실적인 전술 선호',
    affiliation: 'D구 관리국',
    aura: '흑염(어떤 방어도 꿰뚫고 파괴하는 일격필살의 불꽃)',
    combatPower: 'SS',
    speechStyle: '건조하고 짧은 반말',
    weapon: '단검',
    appearance: '흑발, 회색 눈동자',
    imageCode: 'k',
  },
  {
    id: 'l',
    name: '카르마',
    gender: '남',
    age: 45,
    mbti: 'INFJ',
    personality: '피로감, 허무주의, 고독함',
    characteristics: 'Null전쟁의 영웅, 사람을 지키는 강한 신념, 냉혹한 결단',
    affiliation: '무소속',
    aura: '카르마(물리적인 육체, 이능력, 인과율 자체를 단칼에 베어 소멸)',
    combatPower: 'EX',
    speechStyle: '낮고 묵직한 평어, 짙은 피로감이 묻어나는 어조',
    weapon: '검',
    appearance: '흑발, 적안',
    imageCode: 'l',
  },
  {
    id: 'm',
    name: '아르카나',
    gender: '여',
    age: 25,
    mbti: 'ESTJ',
    personality: '냉혹함, 책임감, 현실주의',
    characteristics: '최적의 해답을 선호, 강한 멘탈, 강한 자부심, 약간의 회색지대',
    affiliation: '청염 사무소',
    aura: '청염참(초고온의 푸른 불꽃을 검에 휘감음)',
    combatPower: 'S',
    speechStyle: '단호하고 깔끔한 말투, 직업병이 밴 실무적 어조',
    weapon: '카타나',
    appearance: '갈색 장발, 청안',
    imageCode: 'm',
  },
  {
    id: 'n',
    name: '시리우스',
    gender: '여',
    age: 23,
    mbti: 'ENTP',
    personality: '여유로움, 전략적',
    characteristics: '기만과 심리전의 대가, 변수 창출에 능숙',
    affiliation: '청염 사무소',
    aura: '별자리(카드에 그려진 별자리와 관련된 기믹을 창출)',
    combatPower: 'A',
    speechStyle: '능글맞은 존댓말',
    weapon: '별자리 카드',
    appearance: '하늘색 장발, 청안',
    imageCode: 'n',
  },
  {
    id: 'p',
    name: '블레이즈',
    gender: '여',
    age: 32,
    mbti: 'ESTP',
    personality: '본능적, 통제불능',
    characteristics: '죄악 중 분노를 상징, 광전사, 파괴 본능, 파괴 자체를 즐김',
    affiliation: '7대 죄악',
    aura: '광폭염(뭐든지 순식간에 녹이는 극한의 불꽃)',
    combatPower: 'X',
    speechStyle: '거친 반말, 폭발하는 텐션',
    weapon: '건틀렛',
    appearance: '흐트러진 붉은 장발, 적안',
    imageCode: 'p',
  },
  {
    id: 'q',
    name: '로이즈',
    gender: '여',
    age: 27,
    mbti: 'INFP',
    personality: '허무주의, 나른함, 염세주의',
    characteristics: '선도 악도 아닌, 오로지 자신의 미학이나 변덕에 따라 움직임, 나른한 살의와 가학성',
    affiliation: '사별 사무소',
    aura: '환영(적의 시야를 교란, 정신공격, 공간 자체를 찢어내어 물리적 타격)',
    combatPower: 'SS',
    speechStyle: '나른하고 몽환적인 반말, 은유적인 표현',
    weapon: '없음',
    appearance: '흰 단발, 보라색 눈동자',
    imageCode: 'q',
  },
  {
    id: 'r',
    name: '라이스타',
    gender: '여',
    age: 22,
    mbti: 'ESFP',
    personality: '가학적인, 관심종자',
    characteristics: '자신의 노래로 완벽한 안식을 선물한다고 믿음, 관객의 \'호응\'에 집착',
    affiliation: '사별 사무소',
    aura: '진혼(보라색 음파로 적의 뇌신경을 터트리거나, 광역 정신 조작 음파)',
    combatPower: 'A-',
    speechStyle: '아이돌 팬서비스 화법, 과장된 무대 용어',
    weapon: '마이크',
    appearance: '보라색 포니테일, 보라색 눈동자',
    imageCode: 'r',
  },
  {
    id: 't',
    name: '켄세이',
    gender: '여',
    age: 20,
    mbti: 'ISTP',
    personality: '침착함, 무관심',
    characteristics: '현 시대 최강의 검사(검성), 선악의 구분이 모호, 실력 상승이 유일한 관심사',
    affiliation: '무소속',
    aura: '극검(극한까지 단련된 순수한 검술로 공간마저 갈라버리는 참격)',
    combatPower: 'X',
    speechStyle: '건조하고 짧은 평어',
    weapon: '두 자루의 검',
    appearance: '갈색 단발, 금안',
    imageCode: 't',
  },
  {
    id: 'w',
    name: '그레이트',
    gender: '남',
    age: 26,
    mbti: 'ISTJ',
    personality: '실용주의, 현실적',
    characteristics: '시로 사무소 대장, 과로에 시달림',
    affiliation: '시로 사무소',
    aura: '중압검(질량/중력 조절, 강력한 운동 에너지 방출)',
    combatPower: 'A',
    speechStyle: '피로하고 사무적인 존댓말',
    weapon: '대검',
    appearance: '단정한 금발, 안경, 금안',
    imageCode: 'w',
  },
  {
    id: 'y',
    name: '스페더',
    gender: '여',
    age: 24,
    mbti: 'ESTP',
    personality: '의리있는, 호승적인',
    characteristics: '실전파, 특유의 반항기와 호승심, 탁상공론을 혐오',
    affiliation: '시로 사무소',
    aura: '쾌속(음속에 달하는 속도)',
    combatPower: 'B+',
    speechStyle: '톡톡 쏘는 반말, 성급하고 직선적인 어조',
    weapon: '없음',
    appearance: '은발, 은색 눈동자, 단발',
    imageCode: 'y',
  },
  {
    id: 'z',
    name: '리버린',
    gender: '여',
    age: 24,
    mbti: 'ESFP',
    personality: '실리주의, 마이페이스',
    characteristics: '특유의 여유로움, 눈치 빠른, 자유로운',
    affiliation: '시로 사무소',
    aura: '스타더스트(별들을 소환해 탄환처럼 쏘아내거나, 방어막으로 활용)',
    combatPower: 'B',
    speechStyle: '발랄하고 장난기 넘치는 하이톤',
    weapon: '없음',
    appearance: '금색 포니테일, 금안',
    imageCode: 'z',
  },
  {
    id: 'C',
    name: '화이트',
    gender: '여',
    age: 19,
    mbti: 'INTJ',
    personality: '무자비한, 오만한, 완벽주의',
    characteristics: '쿠로X No.9, 결벽증, 감정의 동요 없음',
    affiliation: '쿠로X',
    aura: '붕괴(타격하는 순간 대상의 물리적 구조를 붕괴)',
    combatPower: 'SS',
    speechStyle: '차갑고 서늘한 존댓말',
    weapon: '금 건틀렛',
    appearance: '흰색 단발, 보라색 눈동자',
    imageCode: 'C',
  },
  {
    id: 'B',
    name: '브라운',
    gender: '남',
    age: 20,
    mbti: 'ISTP',
    personality: '나른한, 무기력한',
    characteristics: '쿠로X No.4, 엄청난 재능의 전투 천재, 전투가 시작되면 매우 파괴적, 다지증',
    affiliation: '쿠로X',
    aura: '카피(한번 본 모든 아우라를 카피해서 사용)',
    combatPower: 'X-',
    speechStyle: '나른하고 짜증 섞인 반말',
    weapon: '없음',
    appearance: '갈색 머리, 적안',
    imageCode: 'B',
  },
  {
    id: 'v',
    name: '세이버',
    gender: '여',
    age: 31,
    mbti: 'INTJ',
    personality: '허무주의, 무감정한',
    characteristics: '前 검성(스스로 내려옴), 항상 극도로 절제된 감정, 지독한 허무주의',
    affiliation: '무소속',
    aura: '묵염검(흑백의 궤적을 남기며 소리 없이 모든 것을 절단하는 지극히 정제된 참격)',
    combatPower: 'SSS',
    speechStyle: '온기가 없는 정중한 존댓말',
    weapon: '도검',
    appearance: '은색 장발, 은색 눈동자',
    imageCode: 'v',
  }
];
